"""Generate a taxonomy coverage report for SkillOps runner cases."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any


def build_case_suite_report(case_roots: list[str | Path]) -> dict[str, Any]:
    cases: list[dict[str, Any]] = []
    for root in case_roots:
        for path in sorted(Path(root).glob("*/*_runner_summary.json")):
            summary = json.loads(path.read_text(encoding="utf-8"))
            candidates_path = path.with_name(path.name.replace("_summary.json", "_skill_candidates.yaml"))
            cases.append(
                {
                    "case_id": summary.get("case_id"),
                    "qid": summary.get("qid"),
                    "primary_failure_type": summary.get("primary_failure_type"),
                    "proposal_count": summary.get("proposal_count"),
                    "gate_decisions": summary.get("gate_decisions"),
                    "summary_path": str(path),
                    "skill_candidates_path": str(candidates_path) if candidates_path.exists() else "",
                }
            )
    counts = Counter(case["primary_failure_type"] for case in cases)
    return {
        "suite_id": "skillops_case_suite_20260605",
        "case_count": len(cases),
        "failure_type_counts": dict(counts),
        "cases": cases,
        "covered_failure_types": sorted(k for k in counts if k != "no_failure_detected"),
        "notes": [
            "Cases are generated by the single-case SkillOps vertical slice runner.",
            "This suite is a taxonomy-coverage demo, not a statistical benchmark.",
        ],
    }


def render_case_suite_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# SkillOps Case Suite Taxonomy Coverage",
        "",
        f"- Suite ID: `{report['suite_id']}`",
        f"- Case count: {report['case_count']}",
        f"- Failure type counts: {report['failure_type_counts']}",
        "",
        "## Cases",
        "",
        "| Case | QID | Primary Type | Proposals | Gate Decisions | Summary |",
        "| --- | --- | --- | ---: | --- | --- |",
    ]
    for case in report["cases"]:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{case['case_id']}`",
                    f"`{case['qid']}`",
                    f"`{case['primary_failure_type']}`",
                    str(case["proposal_count"]),
                    ", ".join(case.get("gate_decisions") or []),
                    f"`{case['summary_path']}`",
                ]
            )
            + " |"
        )
    lines.extend(["", "## Coverage Interpretation", ""])
    covered = ", ".join(f"`{item}`" for item in report["covered_failure_types"])
    lines.append(f"The current runner suite covers: {covered}.")
    lines.append("")
    lines.append("It also includes a `no_failure_detected` success control to check that the loop does not over-propose skills.")
    lines.extend(["", "## Notes", ""])
    lines.extend(f"- {note}" for note in report.get("notes") or [])
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--case_root", action="append", required=True)
    parser.add_argument("--out_json", required=True)
    parser.add_argument("--out_md", required=True)
    args = parser.parse_args()
    report = build_case_suite_report(args.case_root)
    out_json = Path(args.out_json)
    out_md = Path(args.out_md)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    out_md.write_text(render_case_suite_markdown(report), encoding="utf-8")
    print(out_json)
    print(out_md)


if __name__ == "__main__":
    main()

