#!/usr/bin/env python3
"""
Summarize a PageIndex hybrid wrongset package into an action-oriented report.

The input can be either:
  - a .tar.gz generated by the wrongset export pipeline
  - an extracted directory containing all_cases.csv and summary.md
"""

from __future__ import annotations

import argparse
import csv
import io
import tarfile
from collections import Counter
from pathlib import Path
from typing import Iterable


def _read_member_from_tar(path: Path, suffix: str) -> str:
    with tarfile.open(path, "r:gz") as tf:
        for member in tf.getmembers():
            if member.name.endswith(suffix):
                extracted = tf.extractfile(member)
                if extracted is None:
                    continue
                return extracted.read().decode("utf-8-sig")
    raise FileNotFoundError(f"Unable to find {suffix} in {path}")


def _read_text_input(path: Path, suffix: str) -> str:
    if path.is_file() and path.suffixes[-2:] == [".tar", ".gz"]:
        return _read_member_from_tar(path, suffix)
    candidate = path / suffix
    if candidate.exists():
        return candidate.read_text(encoding="utf-8-sig")
    matches = list(path.rglob(suffix))
    if matches:
        return matches[0].read_text(encoding="utf-8-sig")
    raise FileNotFoundError(f"Unable to find {suffix} under {path}")


def _load_rows(path: Path) -> list[dict[str, str]]:
    text = _read_text_input(path, "all_cases.csv")
    return list(csv.DictReader(io.StringIO(text)))


def _counter(rows: Iterable[dict[str, str]], key: str) -> Counter:
    return Counter(row.get(key, "") for row in rows)


def _pct(part: int, total: int) -> str:
    return f"{part / total * 100:.1f}%" if total else "0.0%"


def _short(text: str, limit: int = 120) -> str:
    text = " ".join((text or "").split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


def build_report(rows: list[dict[str, str]]) -> str:
    total = len(rows)
    hybrid_noncorrect = [r for r in rows if r.get("hybrid_verdict") != "CORRECT"]
    regressions = [r for r in rows if r.get("category") in {"hybrid_loss", "hybrid_regressed"}]
    wins = [r for r in rows if r.get("category") == "hybrid_win"]

    generation_rows = [
        r for r in hybrid_noncorrect
        if r.get("hybrid_error_group") == "GENERATION_RELATED"
    ]
    numeric_rows = [
        r for r in hybrid_noncorrect
        if r.get("hybrid_error_group") == "FINANCE_NUMERIC_SEMANTIC"
    ]
    query_rows = [
        r for r in hybrid_noncorrect
        if r.get("hybrid_error_group") == "QUERY_CONTEXT"
    ]

    lines: list[str] = []
    lines.append("# PageIndex Hybrid Fast Feasibility Report")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"- Total cases: {total}")
    lines.append(f"- Hybrid non-correct cases: {len(hybrid_noncorrect)} ({_pct(len(hybrid_noncorrect), total)})")
    lines.append(f"- Hybrid wins: {len(wins)}")
    lines.append(f"- Hybrid losses/regressions: {len(regressions)}")
    lines.append(
        "- Main fast path: keep PageIndex as structural recall, then add source-aware candidate guards "
        "and strict evidence self-check instead of fine-tuning."
    )
    lines.append("")
    lines.append("## Verdict Distribution")
    lines.append("")
    lines.append(f"- Hybrid verdicts: {dict(_counter(rows, 'hybrid_verdict').most_common())}")
    lines.append(f"- Baseline verdicts: {dict(_counter(rows, 'baseline_verdict').most_common())}")
    lines.append(f"- Categories: {dict(_counter(rows, 'category').most_common())}")
    lines.append("")
    lines.append("## Error Concentration")
    lines.append("")
    lines.append(f"- Generation-related hybrid errors: {len(generation_rows)}")
    lines.append(f"- Numeric/table semantic hybrid errors: {len(numeric_rows)}")
    lines.append(f"- Query/context hybrid errors: {len(query_rows)}")
    lines.append(f"- Hybrid error groups: {dict(_counter(hybrid_noncorrect, 'hybrid_error_group').most_common())}")
    lines.append(f"- Hybrid error subtypes: {dict(_counter(hybrid_noncorrect, 'hybrid_error_subtype').most_common())}")
    lines.append("")
    lines.append("## Fast Fix Plan")
    lines.append("")
    lines.append("1. Source-aware PageIndex rerank guard")
    lines.append("   - Add `pageindex_final_cap` to prevent PageIndex candidates from dominating final evidence.")
    lines.append("   - Add `pageindex_score_multiplier` for soft down-weighting when PageIndex creates noise.")
    lines.append("2. Strict answer self-check")
    lines.append("   - Add an optional verifier rewrite that removes unsupported numbers, dates, entity relationships, and product details.")
    lines.append("   - Targets the dominant B1 hallucination/factual-conflict bucket.")
    lines.append("3. Numeric/table discipline")
    lines.append("   - Preserve units, periods, and formulas in prompts now; later route hard table arithmetic to deterministic code.")
    lines.append("4. Regression case review")
    lines.append("   - Focus first on losses/regressions because those are where hybrid hurts an already-correct baseline.")
    lines.append("")
    lines.append("## Initial Experiment Settings")
    lines.append("")
    lines.append("Retrieval ablation command to test the guarded hybrid fusion behavior:")
    lines.append("")
    lines.append("```bash")
    lines.append("BENCHMARKS=\"zeekr\" \\")
    lines.append("PAGEINDEX_TOP_K=10 \\")
    lines.append("PAGEINDEX_NODE_TOP_K=10 \\")
    lines.append("PAGEINDEX_MAX_CHUNKS_PER_NODE=3 \\")
    lines.append("PAGEINDEX_PAGE_WINDOW=0 \\")
    lines.append("PAGEINDEX_FINAL_CAP=2 \\")
    lines.append("PAGEINDEX_SCORE_MULTIPLIER=0.92 \\")
    lines.append("ANSWER_SELF_CHECK=1 \\")
    lines.append("bash test/colm/retrieval/run_pageindex_experiments.sh")
    lines.append("```")
    lines.append("")
    lines.append("End-to-end QA config keys for `batch_qa_test.py` / deployment YAML:")
    lines.append("")
    lines.append("```yaml")
    lines.append("pageindex_mode: \"hybrid\"")
    lines.append("pageindex_top_k: 10")
    lines.append("pageindex_node_top_k: 10")
    lines.append("pageindex_max_chunks_per_node: 3")
    lines.append("pageindex_page_window: 0")
    lines.append("pageindex_final_cap: 2")
    lines.append("pageindex_score_multiplier: 0.92")
    lines.append("answer_self_check_enabled: true")
    lines.append("answer_self_check_max_chars: 12000")
    lines.append("```")
    lines.append("")
    lines.append("## Regression Examples")
    lines.append("")
    for row in regressions[:12]:
        lines.append(
            f"- {row.get('qid')}: {row.get('hybrid_verdict')}/{row.get('baseline_verdict')} "
            f"delta={row.get('delta_score')} "
            f"error={row.get('hybrid_error_group')}:{row.get('hybrid_error_subtype')} - "
            f"{_short(row.get('question', ''))}"
        )
    lines.append("")
    lines.append("## Feasibility Call")
    lines.append("")
    lines.append(
        "A no-finetune improvement is feasible because the wrongset is concentrated in preventable "
        "engineering failure modes: unsupported generation, candidate competition, and table/numeric discipline. "
        "It is not realistic to guarantee near-100% open-domain correctness, but it is realistic to target a "
        "large fixed-set improvement with the guarded hybrid plus verifier path."
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("wrongset_path", type=Path)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    rows = _load_rows(args.wrongset_path)
    report = build_report(rows)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report, encoding="utf-8")
    else:
        print(report)


if __name__ == "__main__":
    main()
