#!/usr/bin/env bash
# Assemble resources/runtime for the private-fund Electron desktop package.
# Runs inside WSL/Linux. Produces a slim project tree + WSL bridge scripts +
# desktop.env (non-secret process defaults). Native Windows Python runtime
# is optional (see assemble_win_python.sh); WSL bridge is the reliable path for
# testing the Windows installer on a machine that already has this monorepo in WSL.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ELECTRON_DIR="$ROOT_DIR/omnigent/web/electron"
RUNTIME_DIR="${RUNTIME_OUT:-$ELECTRON_DIR/resources/runtime}"

echo "==> Assembling desktop runtime at $RUNTIME_DIR"
rm -rf "$RUNTIME_DIR"
mkdir -p "$RUNTIME_DIR"/{bin,config,project}

# --- Slim project: only what private-fund needs ---
PROJECT="$RUNTIME_DIR/project"
mkdir -p "$PROJECT/FinSagent/data_pipeline"
mkdir -p "$PROJECT/src"
mkdir -p "$PROJECT/output/private_fund_datasets"
mkdir -p "$PROJECT/scripts"

# FinSagent: config fields → desktop.env; pipeline only (no deploy/UI/eval)
echo "==> Copying FinSagent data_pipeline (slim)"
# Core ingest modules + direct helpers; skip heavy legacy SEC batch trees if huge
rsync -a --delete \
  --exclude '__pycache__' \
  --exclude '*.pyc' \
  --exclude 'file2chunk' \
  "$ROOT_DIR/FinSagent/data_pipeline/" \
  "$PROJECT/FinSagent/data_pipeline/"

# pdf_research_demo used by omnigent private_fund routes
echo "==> Copying src/pdf_research_demo"
rsync -a --delete \
  --exclude '__pycache__' \
  --exclude '*.pyc' \
  "$ROOT_DIR/src/pdf_research_demo/" \
  "$PROJECT/src/pdf_research_demo/"
# package marker
touch "$PROJECT/src/__init__.py" 2>/dev/null || true

# Omnigent source (server serves static web-ui from package path)
echo "==> Copying omnigent package source (no .venv / web node_modules)"
rsync -a \
  --exclude '.venv' \
  --exclude 'web/node_modules' \
  --exclude 'web/electron/node_modules' \
  --exclude 'web/electron/dist' \
  --exclude 'web/electron/resources' \
  --exclude '**/__pycache__' \
  --exclude '**/*.pyc' \
  --exclude '.git' \
  --exclude 'tests' \
  --exclude 'examples' \
  "$ROOT_DIR/omnigent/" \
  "$PROJECT/omnigent/"

# Ensure web-ui static exists (copy from monorepo if present)
if [[ -f "$ROOT_DIR/omnigent/omnigent/server/static/web-ui/index.html" ]]; then
  echo "==> web-ui already present in omnigent package"
else
  echo "WARN: web-ui static missing; run: cd omnigent/web && npm run build" >&2
fi

# Manage scripts for WSL bridge
cp "$ROOT_DIR/scripts/manage_omnigent_services.sh" "$PROJECT/scripts/"
cp "$ROOT_DIR/scripts/start_litellm_dashscope.sh" "$PROJECT/scripts/"
chmod +x "$PROJECT/scripts/"*.sh

# Marker for PRIVATE_FUND_PROJECT_ROOT resolution
mkdir -p "$PROJECT/output/private_fund_datasets"
touch "$PROJECT/output/private_fund_datasets/.keep"

cat > "$RUNTIME_DIR/config/desktop.env" <<EOF
# Generated by scripts/desktop/assemble_runtime.sh. LLM credentials are user Settings.
DESKTOP_MODE=bundled
LITELLM_HOST=127.0.0.1
LITELLM_PORT=4000
OMNIGENT_SERVER_HOST=127.0.0.1
OMNIGENT_SERVER_PORT=6767
OMNIGENT_AUTH_ENABLED=0
OMNIGENT_LOCAL_SINGLE_USER=1
OMNIGENT_NO_UPDATE_CHECK=1
ANTHROPIC_AUTH_TOKEN=sk-local-cc-haha
# WSL bridge (Windows installer testing against this monorepo)
DESKTOP_WSL_DISTRO=Ubuntu
DESKTOP_WSL_PROJECT_ROOT=/home/code/pravite_fund_ai_research
EOF

# Example without secrets for git
cat > "$RUNTIME_DIR/config/desktop.env.example" <<'EOF'
DESKTOP_MODE=bundled
LITELLM_HOST=127.0.0.1
LITELLM_PORT=4000
OMNIGENT_SERVER_HOST=127.0.0.1
OMNIGENT_SERVER_PORT=6767
DESKTOP_WSL_DISTRO=Ubuntu
DESKTOP_WSL_PROJECT_ROOT=/home/code/pravite_fund_ai_research
EOF

# Runtime-generated by Electron; this is a non-secret compatibility placeholder.
cat > "$RUNTIME_DIR/config/litellm.yaml" <<'EOF'
model_list: []
EOF

# --- WSL bridge scripts (Windows Electron → start monorepo stack in Ubuntu) ---
cat > "$RUNTIME_DIR/bin/start_stack_wsl.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
# Called from Windows via: wsl.exe -d Ubuntu -e bash <this script>
# The script path may be a Windows-mounted path; re-exec from project when possible.

PROJECT_ROOT="${DESKTOP_WSL_PROJECT_ROOT:-/home/code/pravite_fund_ai_research}"
if [[ ! -d "$PROJECT_ROOT" ]]; then
  echo "WSL project root not found: $PROJECT_ROOT" >&2
  exit 1
fi
export PATH="${HOME}/.bun/bin:${HOME}/.local/bin:${PATH}"
cd "$PROJECT_ROOT"
# Prefer monorepo manage script (tmux stack already used in dev)
exec bash "$PROJECT_ROOT/scripts/manage_omnigent_services.sh" start
EOF
chmod +x "$RUNTIME_DIR/bin/start_stack_wsl.sh"

cat > "$RUNTIME_DIR/bin/stop_stack_wsl.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
PROJECT_ROOT="${DESKTOP_WSL_PROJECT_ROOT:-/home/code/pravite_fund_ai_research}"
export PATH="${HOME}/.bun/bin:${HOME}/.local/bin:${PATH}"
exec bash "$PROJECT_ROOT/scripts/manage_omnigent_services.sh" stop
EOF
chmod +x "$RUNTIME_DIR/bin/stop_stack_wsl.sh"

# Windows helper bat that wraps wsl (optional manual use)
cat > "$RUNTIME_DIR/bin/start_stack_wsl.cmd" <<'EOF'
@echo off
set DISTRO=%DESKTOP_WSL_DISTRO%
if "%DISTRO%"=="" set DISTRO=Ubuntu
wsl.exe -d %DISTRO% -e bash -lc "export DESKTOP_WSL_PROJECT_ROOT=/home/code/pravite_fund_ai_research; bash /home/code/pravite_fund_ai_research/omnigent/web/electron/resources/runtime/bin/start_stack_wsl.sh"
EOF

echo "$ROOT_DIR" > "$RUNTIME_DIR/VERSION"
date -u +"%Y-%m-%dT%H:%M:%SZ" >> "$RUNTIME_DIR/VERSION"
echo "assemble_runtime: ok"
du -sh "$RUNTIME_DIR" || true
