#!/usr/bin/env bash
# Assemble resources/runtime for the private-fund Electron desktop package.
# Runs inside WSL/Linux. Produces a slim project tree + WSL bridge scripts +
# desktop.env (LLM keys injected at build time). Native Windows Python runtime
# is optional (see assemble_win_python.sh); WSL bridge is the reliable path for
# testing the Windows installer on a machine that already has this monorepo in WSL.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ELECTRON_DIR="$ROOT_DIR/omnigent/web/electron"
RUNTIME_DIR="${RUNTIME_OUT:-$ELECTRON_DIR/resources/runtime}"
FINSAGENT_CONFIG="${FINSAGENT_CONFIG:-$ROOT_DIR/FinSagent/config/production.yaml}"

echo "==> Assembling desktop runtime at $RUNTIME_DIR"
rm -rf "$RUNTIME_DIR"
mkdir -p "$RUNTIME_DIR"/{bin,config,project}

# --- Slim project: only what private-fund needs ---
PROJECT="$RUNTIME_DIR/project"
mkdir -p "$PROJECT/FinSagent/data_pipeline"
mkdir -p "$PROJECT/src"
mkdir -p "$PROJECT/output/private_fund_datasets"
mkdir -p "$PROJECT/scripts"

# FinSagent: config fields → desktop.env; pipeline only (no deploy/UI/eval)
echo "==> Copying FinSagent data_pipeline (slim)"
# Core ingest modules + direct helpers; skip heavy legacy SEC batch trees if huge
rsync -a --delete \
  --exclude '__pycache__' \
  --exclude '*.pyc' \
  --exclude 'file2chunk' \
  "$ROOT_DIR/FinSagent/data_pipeline/" \
  "$PROJECT/FinSagent/data_pipeline/"

# pdf_research_demo used by omnigent private_fund routes
echo "==> Copying src/pdf_research_demo"
rsync -a --delete \
  --exclude '__pycache__' \
  --exclude '*.pyc' \
  "$ROOT_DIR/src/pdf_research_demo/" \
  "$PROJECT/src/pdf_research_demo/"
# package marker
touch "$PROJECT/src/__init__.py" 2>/dev/null || true

# Omnigent source (server serves static web-ui from package path)
echo "==> Copying omnigent package source (no .venv / web node_modules)"
rsync -a \
  --exclude '.venv' \
  --exclude 'web/node_modules' \
  --exclude 'web/electron/node_modules' \
  --exclude 'web/electron/dist' \
  --exclude 'web/electron/resources' \
  --exclude '**/__pycache__' \
  --exclude '**/*.pyc' \
  --exclude '.git' \
  --exclude 'tests' \
  --exclude 'examples' \
  "$ROOT_DIR/omnigent/" \
  "$PROJECT/omnigent/"

# Ensure web-ui static exists (copy from monorepo if present)
if [[ -f "$ROOT_DIR/omnigent/omnigent/server/static/web-ui/index.html" ]]; then
  echo "==> web-ui already present in omnigent package"
else
  echo "WARN: web-ui static missing; run: cd omnigent/web && npm run build" >&2
fi

# Manage scripts for WSL bridge
cp "$ROOT_DIR/scripts/manage_omnigent_services.sh" "$PROJECT/scripts/"
cp "$ROOT_DIR/scripts/start_litellm_dashscope.sh" "$PROJECT/scripts/"
chmod +x "$PROJECT/scripts/"*.sh

# Marker for PRIVATE_FUND_PROJECT_ROOT resolution
mkdir -p "$PROJECT/output/private_fund_datasets"
touch "$PROJECT/output/private_fund_datasets/.keep"

# --- desktop.env from FinSagent config / env overrides ---
read_yaml_value() {
  local key="$1"
  python3 - "$FINSAGENT_CONFIG" "$key" <<'PY'
import re, sys
from pathlib import Path
path = Path(sys.argv[1]); key = sys.argv[2]
pattern = re.compile(rf"^\s*{re.escape(key)}\s*:\s*(.*?)\s*$")
for line in path.read_text(encoding="utf-8").splitlines():
    m = pattern.match(line)
    if m:
        value = m.group(1).strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        print(value)
        raise SystemExit(0)
raise SystemExit(1)
PY
}

MODEL="${LITELLM_TARGET_MODEL_NAME:-}"
BASE="${LITELLM_TARGET_API_BASE:-}"
KEY="${LITELLM_TARGET_API_KEY:-}"
if [[ -z "$MODEL" && -f "$FINSAGENT_CONFIG" ]]; then MODEL="$(read_yaml_value llm_model_name || true)"; fi
if [[ -z "$BASE" && -f "$FINSAGENT_CONFIG" ]]; then BASE="$(read_yaml_value llm_base_url || true)"; fi
if [[ -z "$KEY" && -f "$FINSAGENT_CONFIG" ]]; then KEY="$(read_yaml_value llm_api_key || true)"; fi
MODEL="${MODEL:-qwen3-max}"
BASE="${BASE:-https://dashscope.aliyuncs.com/compatible-mode/v1}"
if [[ -z "$KEY" ]]; then
  echo "WARN: No LLM API key found. Set LITELLM_TARGET_API_KEY or FinSagent config." >&2
  KEY="REPLACE_ME_AT_BUILD"
fi

PROVIDER="${LITELLM_TARGET_PROVIDER:-}"
if [[ -z "$PROVIDER" ]]; then
  case "$BASE" in
    *deepseek*) PROVIDER="deepseek" ;;
    *dashscope*) PROVIDER="dashscope" ;;
    *) PROVIDER="openai" ;;
  esac
fi

cat > "$RUNTIME_DIR/config/desktop.env" <<EOF
# Generated by scripts/desktop/assemble_runtime.sh — do not commit real keys to git.
DESKTOP_MODE=bundled
LITELLM_TARGET_MODEL_NAME=$MODEL
LITELLM_TARGET_API_BASE=$BASE
LITELLM_TARGET_API_KEY=$KEY
LITELLM_TARGET_PROVIDER=$PROVIDER
LITELLM_HOST=127.0.0.1
LITELLM_PORT=4000
OMNIGENT_SERVER_HOST=127.0.0.1
OMNIGENT_SERVER_PORT=6767
OMNIGENT_AUTH_ENABLED=0
OMNIGENT_LOCAL_SINGLE_USER=1
OMNIGENT_NO_UPDATE_CHECK=1
ANTHROPIC_MODEL=$MODEL
ANTHROPIC_AUTH_TOKEN=sk-local-cc-haha
# WSL bridge (Windows installer testing against this monorepo)
DESKTOP_WSL_DISTRO=Ubuntu
DESKTOP_WSL_PROJECT_ROOT=/home/code/pravite_fund_ai_research
EOF

# Example without secrets for git
cat > "$RUNTIME_DIR/config/desktop.env.example" <<'EOF'
DESKTOP_MODE=bundled
LITELLM_TARGET_MODEL_NAME=qwen3-max
LITELLM_TARGET_API_BASE=https://dashscope.aliyuncs.com/compatible-mode/v1
LITELLM_TARGET_API_KEY=
LITELLM_TARGET_PROVIDER=dashscope
LITELLM_HOST=127.0.0.1
LITELLM_PORT=4000
OMNIGENT_SERVER_HOST=127.0.0.1
OMNIGENT_SERVER_PORT=6767
DESKTOP_WSL_DISTRO=Ubuntu
DESKTOP_WSL_PROJECT_ROOT=/home/code/pravite_fund_ai_research
EOF

# LiteLLM yaml template (keys from env)
TARGET_MODEL="$PROVIDER/$MODEL"
python3 - "$RUNTIME_DIR/config/litellm.yaml" "$MODEL" "$TARGET_MODEL" <<'PY'
import sys
from pathlib import Path
path = Path(sys.argv[1])
model_name = sys.argv[2]
target_model = sys.argv[3]
names = [model_name, "claude-sonnet-4-6", "claude-sonnet-4-5", "claude-opus-4-6", "claude-haiku-4-5"]
lines = ["model_list:"]
for name in names:
    lines += [
        f"  - model_name: {name}",
        "    litellm_params:",
        f"      model: {target_model}",
        "      api_base: os.environ/LITELLM_TARGET_API_BASE",
        "      api_key: os.environ/LITELLM_TARGET_API_KEY",
    ]
lines += ["", "litellm_settings:", "  drop_params: true", "  request_timeout: 600", ""]
path.write_text("\n".join(lines), encoding="utf-8")
PY

# --- WSL bridge scripts (Windows Electron → start monorepo stack in Ubuntu) ---
cat > "$RUNTIME_DIR/bin/start_stack_wsl.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
# Called from Windows via: wsl.exe -d Ubuntu -e bash <this script>
# The script path may be a Windows-mounted path; re-exec from project when possible.

PROJECT_ROOT="${DESKTOP_WSL_PROJECT_ROOT:-/home/code/pravite_fund_ai_research}"
if [[ ! -d "$PROJECT_ROOT" ]]; then
  echo "WSL project root not found: $PROJECT_ROOT" >&2
  exit 1
fi
export PATH="${HOME}/.bun/bin:${HOME}/.local/bin:${PATH}"
cd "$PROJECT_ROOT"
# Prefer monorepo manage script (tmux stack already used in dev)
exec bash "$PROJECT_ROOT/scripts/manage_omnigent_services.sh" start
EOF
chmod +x "$RUNTIME_DIR/bin/start_stack_wsl.sh"

cat > "$RUNTIME_DIR/bin/stop_stack_wsl.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
PROJECT_ROOT="${DESKTOP_WSL_PROJECT_ROOT:-/home/code/pravite_fund_ai_research}"
export PATH="${HOME}/.bun/bin:${HOME}/.local/bin:${PATH}"
exec bash "$PROJECT_ROOT/scripts/manage_omnigent_services.sh" stop
EOF
chmod +x "$RUNTIME_DIR/bin/stop_stack_wsl.sh"

# Windows helper bat that wraps wsl (optional manual use)
cat > "$RUNTIME_DIR/bin/start_stack_wsl.cmd" <<'EOF'
@echo off
set DISTRO=%DESKTOP_WSL_DISTRO%
if "%DISTRO%"=="" set DISTRO=Ubuntu
wsl.exe -d %DISTRO% -e bash -lc "export DESKTOP_WSL_PROJECT_ROOT=/home/code/pravite_fund_ai_research; bash /home/code/pravite_fund_ai_research/omnigent/web/electron/resources/runtime/bin/start_stack_wsl.sh"
EOF

echo "$ROOT_DIR" > "$RUNTIME_DIR/VERSION"
date -u +"%Y-%m-%dT%H:%M:%SZ" >> "$RUNTIME_DIR/VERSION"
echo "assemble_runtime: ok"
du -sh "$RUNTIME_DIR" || true
